[package]
name = "advent-of-code-2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-setup = { git = "https://github.com/PhazonicRidley/aoc-setup.git", branch = "main"}